language: java
jdk:
  - oraclejdk8
script:
  - mvn install -DskipTests=true
  - mvn test
  - mvn install -DskipTests=true -Pmockito2
  - mvn test -Pmockito2

before_install:
  - pip install --user codecov
after_success:
  - codecov